name: Workflow branch test 

on: 
  push:
    branches:
      - 'main'
      
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: echo "Welcome to the repository!"
