name: Test workflow
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-ceffee29-c799-470c-958c-dc5cbe956790.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on: 
  push:
    branches:
      - 'main'
      
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest

